version: 2.1
jobs:
  run-test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Run Tests
          command: npm test --json --outputFile=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
  run-build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
      - run:
          name: Install Dependencies
          command: npm ci
      - save_cache:
          key: npm-cache-v1-{{ checksum "package-lock.json" }}
          paths:
            - /home/circleci/.npm
      - run:
          name: Build Package
          command: npm build
  run-publish:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: Publish to npm
          command: |
            npm set //registry.npmjs.org/:_authToken=5812c23c-1359-417c-979b-f6a85a49fd3d
            npm publish
workflows:
  build-test:
    jobs:
      - run-test
      - run-build:
          requires:
            - run-test
      - run-publish:
          requires:
            - run-build
# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test

