version: 2.1
jobs:
  run-test:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - run:
          name: "Install dependencies"
          command: |
            npm install --save
      - run:
          name: "Run tests"
          command: |
            ./node_modules/jest/bin/jest --json --outputFile=test-results
      - store_test_results:
          path: test-results
      - store_artifacts:
          path: test-results
workflows:
  build-test:
    jobs:
      - run-test
# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test

