version: 2.1
orbs:
  node: circleci/node@4.1.0
jobs:
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test --passWithNoTests
          name: Test the WiPay package modules.
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run build
          name: Build the WiPay distributable package
      - persist_to_workspace:
          root: /
          path: build
  publish:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: /tmp/build
      - checkout
      - run:
          name: Publish node-wipay to NPM.
          command: |
            npm set //registry.npmjs.org/:_authToken=90099e06-409c-4fb1-a135-d83c793484b5
            npm publish
workflows:
  release:
    jobs:
      - test
      - build:
          requires:
            - test
      - publish:
          requires:
            - build
# version: 2.1
# orbs:
#   node: circleci/node@3.0.0
# workflows:
#   node-tests:
#     jobs:
#       - node/test

